### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by nam-co** [nahidulhasan/laravel-html2pdf#1]
Hi thanks for the package, I was widening if your html2pdf is compatible with css files (Bootstrap 4) and @import google fonts? thanks for any help

**Comment by nahidulhasan** [comment]
Hi @nam-co,
html2pdf is compatible with Bootstrap 4 and google fonts.

**Comment by nam-co** [comment]
I believe wkhtmltopdf 0.12.5 is necessary for Ubuntu 18

**Comment by nahidulhasan** [comment]
You can follow this link  
https://www.odoo.com/forum/help-1/question/ubuntu-18-04-lts-how-to-install-wkhtmltopdf-0-12-1-134198
